[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions."sync-manutencao"]
  schedule = "*/2 * * * *"

[[redirects]]
  from = "/presenca-link/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
